2025-04-29 07:13:29,001 INFO    MainThread:63023 [wandb_setup.py:_flush():68] Current SDK version is 0.19.10
2025-04-29 07:13:29,002 INFO    MainThread:63023 [wandb_setup.py:_flush():68] Configure stats pid to 63023
2025-04-29 07:13:29,002 INFO    MainThread:63023 [wandb_setup.py:_flush():68] Loading settings from /home/ubuntu/.config/wandb/settings
2025-04-29 07:13:29,002 INFO    MainThread:63023 [wandb_setup.py:_flush():68] Loading settings from /home/ubuntu/world-mar/wandb/settings
2025-04-29 07:13:29,002 INFO    MainThread:63023 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-04-29 07:13:29,002 INFO    MainThread:63023 [wandb_init.py:setup_run_log_directory():724] Logging user logs to ./wandb/run-20250429_071329-itf3e01d/logs/debug.log
2025-04-29 07:13:29,002 INFO    MainThread:63023 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to ./wandb/run-20250429_071329-itf3e01d/logs/debug-internal.log
2025-04-29 07:13:29,002 INFO    MainThread:63023 [wandb_init.py:init():852] calling init triggers
2025-04-29 07:13:29,002 INFO    MainThread:63023 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-04-29 07:13:29,002 INFO    MainThread:63023 [wandb_init.py:init():893] starting backend
2025-04-29 07:13:29,002 INFO    MainThread:63023 [wandb_init.py:init():897] sending inform_init request
2025-04-29 07:13:29,093 INFO    MainThread:63023 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-29 07:13:29,093 INFO    MainThread:63023 [wandb_init.py:init():907] backend started and connected
2025-04-29 07:13:29,097 INFO    MainThread:63023 [wandb_init.py:init():1002] updated telemetry
2025-04-29 07:13:29,188 INFO    MainThread:63023 [wandb_init.py:init():1026] communicating run to backend with 90.0 second timeout
2025-04-29 07:13:29,614 INFO    MainThread:63023 [wandb_init.py:init():1101] starting run threads in backend
2025-04-29 07:13:29,704 INFO    MainThread:63023 [wandb_run.py:_console_start():2566] atexit reg
2025-04-29 07:13:29,704 INFO    MainThread:63023 [wandb_run.py:_redirect():2414] redirect: wrap_raw
2025-04-29 07:13:29,705 INFO    MainThread:63023 [wandb_run.py:_redirect():2483] Wrapping output streams.
2025-04-29 07:13:29,705 INFO    MainThread:63023 [wandb_run.py:_redirect():2506] Redirects installed.
2025-04-29 07:13:29,706 INFO    MainThread:63023 [wandb_init.py:init():1147] run started, returning control to user process
2025-04-29 07:14:02,897 INFO    MsgRouterThr:63023 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-04-29 07:14:03,855 ERROR   MainThread:63023 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2487, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-29 07:14:03,856 ERROR   MainThread:63023 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2487, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1632, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 763, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/ubuntu/miniconda3/envs/world-mar/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
